export interface TimezoneOption {
  value: string;
  label: string;
}

export const TIMEZONES: TimezoneOption[] = [
  { value: "Europe/London", label: "London (UK)" },
  { value: "Europe/Paris", label: "Paris (France)" },
  { value: "Europe/Berlin", label: "Berlin (Germany)" },
  { value: "America/New_York", label: "New York (USA)" },
  { value: "America/Chicago", label: "Chicago (USA)" },
  { value: "America/Los_Angeles", label: "Los Angeles (USA)" },
  { value: "America/Toronto", label: "Toronto (Canada)" },
  { value: "Asia/Dubai", label: "Dubai (UAE)" },
  { value: "Asia/Kolkata", label: "Kolkata (India)" },
  { value: "Asia/Singapore", label: "Singapore" },
  { value: "Asia/Tokyo", label: "Tokyo (Japan)" },
  { value: "Australia/Sydney", label: "Sydney (Australia)" },
  { value: "Europe/Amsterdam", label: "Amsterdam (Netherlands)" },
  { value: "Europe/Madrid", label: "Madrid (Spain)" },
  { value: "Europe/Rome", label: "Rome (Italy)" },
  { value: "Europe/Zurich", label: "Zurich (Switzerland)" },
  { value: "Europe/Stockholm", label: "Stockholm (Sweden)" },
  { value: "Europe/Warsaw", label: "Warsaw (Poland)" },
  { value: "Europe/Dublin", label: "Dublin (Ireland)" },
  { value: "Europe/Lisbon", label: "Lisbon (Portugal)" },
  { value: "America/Denver", label: "Denver (USA)" },
  { value: "America/Phoenix", label: "Phoenix (USA)" },
  { value: "America/Vancouver", label: "Vancouver (Canada)" },
  { value: "America/Mexico_City", label: "Mexico City (Mexico)" },
  { value: "America/Sao_Paulo", label: "São Paulo (Brazil)" },
  { value: "America/Buenos_Aires", label: "Buenos Aires (Argentina)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong" },
  { value: "Asia/Seoul", label: "Seoul (South Korea)" },
  { value: "Asia/Shanghai", label: "Shanghai (China)" },
  { value: "Asia/Bangkok", label: "Bangkok (Thailand)" },
  { value: "Asia/Jakarta", label: "Jakarta (Indonesia)" },
  { value: "Asia/Manila", label: "Manila (Philippines)" },
  { value: "Asia/Kuala_Lumpur", label: "Kuala Lumpur (Malaysia)" },
  { value: "Africa/Johannesburg", label: "Johannesburg (South Africa)" },
  { value: "Africa/Nairobi", label: "Nairobi (Kenya)" },
  { value: "Australia/Melbourne", label: "Melbourne (Australia)" },
  { value: "Pacific/Auckland", label: "Auckland (New Zealand)" },
];

